apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres-warehouse
    access: proxy
    url: postgres:5432
    user: postgres
    database: warehouse
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres
