apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres-warehouse
    access: proxy
    url: postgres:5432
    user: postgres
    database: warehouse
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres

  - name: Postgres userKeys
    type: postgres
    uid: postgres-userkeys
    access: proxy
    url: postgres:5432
    user: postgres
    database: userkeys
    isDefault: false
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres

  - name: Prometheus
    type: prometheus
    uid: prometheus-pipeline
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
