server:
  port: ${SERVER_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  kafka:
    bootstrap-servers: ${KAFKA_HOST_LOCAL:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    topic: ${KAFKA_TOPIC:events}

minio:
  endpoint: http://${MINIO_HOST_LOCAL:localhost}:${MINIO_PORT:9000}
  access-key: ${MINIO_ROOT_USER:minio}
  secret-key: ${MINIO_ROOT_PASSWORD:minio123}
  bucket: ${MINIO_BUCKET:images}
  connect-timeout-secs: ${MINIO_CONNECT_TIMEOUT_SECS:5}
  write-timeout-secs: ${MINIO_WRITE_TIMEOUT_SECS:30}
  read-timeout-secs: ${MINIO_READ_TIMEOUT_SECS:30}
